pipeline:
  hi:
    image: alpine
    commands:
      - flock /lock sh -c 'sleep 5; echo "hi";'
    volumes:
      - /locks/osie/lock:/lock
  hello:
    image: alpine
    commands:
      - flock /lock sh -c 'sleep 5; echo "${greet}";'
    volumes:
      - /locks/osie/lock:/lock
  done:
    image: alpine
    commands:
      - echo "done"
matrix:
  greet:
    - hello
    - hola
