pipeline: 
  build-x86_64:
    image: alpine
    group: build
    commands:
      - echo make build/osie-x86_64.tar.gz
      - sleep 2
  build-aarch64:
    image: alpine
    group: build
    commands:
      - echo make build/osie-aarch64.tar.gz
      - sleep 2

  test-aarch64-ubuntu_16_04:
    image: alpine
    group: test
    commands:
      - echo OS=ubuntu_16_04 make test-aarch64
  test-aarch64-ubuntu_17_10:
    image: alpine
    group: test
    commands:
      - echo OS=ubuntu_17_10 make test-aarch64

  test-x86_64-ubuntu_16_04:
    image: alpine
    group: test
    commands:
      - echo OS=ubuntu_16_04 make test-x86_64
  test-x86_64-ubuntu_17_10:
    image: alpine
    group: test
    commands:
      - echo OS=ubuntu_17_10 make test-x86_64

