pipeline:
  hi:
    image: alpine
    group: simple
    commands:
      - sleep 5
      - echo "hi"
  hello:
    image: alpine
    group: simple
    commands:
      - sleep 5
      - echo "${greet}"
  done:
    image: alpine
    commands:
      - echo "done"
matrix:
  greet:
    - hello
    - hola
