pipeline:
  greet: &greet
    image: alpine
    commands:
      - sleep 5
      - echo "$greet"
  hi:
    <<: *greet
    environment:
      greet=hi
  hello:
    <<: *greet
    environment:
      greet=hello
  hola:
    <<: *greet
    environment:
      greet=hola
  done:
    image: alpine
    commands:
      - echo "done"
